---

- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: Verify YUM repos
  uri: url={{ item.value }}
  with_dict: "{{ yumrepo_repos }}"

- name: Clean existed repos
  shell: rm -rf /etc/yum.repos.d/*.repo

- name: Configure additional repos in /etc/yum.repos.d/
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
  register: repo_file
  with_dict: "{{ yumrepo_repos }}"
  when: yumrepo_repos.keys() | length > 0

- name: Clean yum cache
  shell: yum clean all

