---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Set the correct timezone.
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

- include: ntp_master.yml
  when: ntp_master is defined and ntp_master

- include: ntp_client.yml
  when: ntp_master is undefined
