---
# tasks file for ansible-role-hosts-deploy

- name: Remove existed sunruniaas-manager package
  yum: name=sunruniaas-mgmt state=absent
  when: clean_existed_mgmt

- name: Remove existed info file
  file: path=/var/lib/sunrun/bluemanager/manager.info state=absent
  when: clean_existed_mgmt

- name: Install sunruniaas-manager packages
  shell: yum localinstall {{ item }} -y
  with_items:
    - /opt/sunrun/rpms/files/sunruniaas-pypi*
    - /opt/sunrun/rpms/files/sunruniaas-manager*

- name: Prepare /opt/sunrun/etc directory
  file: path=/opt/sunrun/etc state=directory mode=0755

- name: Configure bluemanager.cfg
  template: src=etc/bluemanager.cfg.j2 dest=/opt/sunrun/etc/bluemanager.cfg owner=root group=root mode=0644
  tags:
    - config_mgmt

- name: Migrate database
  shell: /opt/sunrun/bluemanager/bin/syncdb
  run_once: yes

- name: Start bluemanager service
  service:
    name: sunruniaas-mgmt
    state: restarted
    enabled: yes
