---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
#
## Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure GlusterFS is started and enabled at boot.
  service: "name={{ glusterfs_daemon }} state=restarted enabled=yes"

- name: Configure GlusterFS cluster
  include: configure.yml
