---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: GlusterFS installation for Linux.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.8
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  galaxy_tags:
    - system
    - networking
    - cloud
    - clustering
