---
# tasks file for ansible-role-hosts-deploy

- name: Remove existed package
  yum: name=sunrun-hac state=absent
  when: clean_existed_hac

- name: Install sunrun-hac packages
  shell: yum localinstall {{ item }} -y
  with_items:
    - /opt/sunrun/rpms/files/sunrun-hac*

- name: Prepare /etc/sunrun directory
  file: path=/etc/sunrun state=directory mode=0755

- name: Configure srhac.cfg
  template: src=etc/sunrun/srhac.conf.j2 dest=/etc/sunrun/srhac.conf owner=root group=root mode=0644

- name: Start bluemanager service
  shell: /etc/init.d/srhac restart




